version: "3.9"
services:
  fb:
    build:
      context: docker
    image: filebrowser:latest
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./data:/data
    - ./config:/config
    ports:
    - 8000:8000
