version: "3.9"

services:
  homepage:
    build:
      context: .
      args:
        BUILD_DATE: "2024-01-01T00:00:00Z"
        VERSION: "latest"
        COMMIT_BRANCH: "main"
    image: homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker integration
    environment:
      # User/Group Configuration
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Application Configuration
      - PORT=3000
    networks:
      - homepage

networks:
  homepage:
    name: homepage
    driver: bridge
